twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths: 
        'public/uploads/beats': beats

when@test:
    twig:
        strict_variables: true
